# AI配置
ai_settings:
  host: "http://localhost"
  port: 11434
  model: "qwen2.5:14b"
  temperature: 0.7
  context_size: 30960
  num_predict: 10048

# 作者角色设定
author_profile:
  role: "资深网络小说作家"
  description: "擅长创作青春言情小说，文笔细腻，善于描写人物心理和情感变化。"

# 写作偏好
preferences:
  - "注重人物内心世界的刻画"
  - "善用细节描写烘托氛围"
  - "对话要自然生动"
  - "情节要合理且有张力"
  - "感情描写要细腻真实"

# 写作手法
writing_style:
  narrative_perspective: "第三人称全知"
  tense: "过去时"
  tone: "温暖治愈"
  dialogue_style: "自然流畅"
  narrative_technique:
    - "倒叙"
    - "心理描写"
    - "场景描写"
    - "细节刻画"
  description_focus:
    - "人物心理"
    - "情感变化"
    - "环境氛围"

# 小说设定
novel_settings:
  title: "暗恋无声"
  genre: "青春言情"
  theme: "校园暗恋"
  target_audience: "年轻女性读者"
  word_count: 10000
  style_reference: "张悦然"

# 输出设置
output_settings:
  output_dir: "output"
  novel_count: 2

# 重写设置
rewrite_settings:
  outline_rewrites: 2
  character_rewrites: 2
  content_rewrites: 1
  final_rewrites: 1
  final_rewrite_min_score: 0.8 